version: '3.4'
services:
  audit-share-share:
    image: alfresco-share-audit-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-share-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: audit-share-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  audit-share-acs:
    image: alfresco-content-services-audit-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-share-platform-docker/target
      network: host
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - audit-share-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - audit-share-postgres
  audit-share-postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - audit-share-db-volume:/var/lib/postgresql/data
  audit-share-ass:
    image: alfresco/alfresco-search-services:2.0.1.1
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-share-ass-docker/target
    environment:
      SOLR_ALFRESCO_HOST: audit-share-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: audit-share-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    ports:
      - "8983:8983"
    volumes:
      - audit-share-ass-volume:/opt/alfresco-search-services/contentstore
      - audit-share-ass-volume:/opt/alfresco-search-services/data
  libreoffice:
    image: alfresco/alfresco-libreoffice:2.5.1
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
    ports:
      - 8092:8090
  alfresco-pdf-renderer:
    image: alfresco/alfresco-pdf-renderer:2.5.1
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
    ports:
      - 8090:8090
  imagemagick:
    image: alfresco/alfresco-imagemagick:2.5.1
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
    ports:
      - 8091:8090
  tika:
    image: alfresco/alfresco-tika:2.5.1
    environment:
      JAVA_OPTS: ' -Xms256m -Xmx512m'
    ports:
      - 8093:8090
  transform-misc:
    image: alfresco/alfresco-transform-misc:2.5.1
    environment:
      JAVA_OPTS: ' -Xms256m -Xmx512m'
    ports:
      - 8094:8090
  activemq:
    image: alfresco/alfresco-activemq:5.16.1
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
volumes:
  audit-share-acs-volume:
    external: true
  audit-share-db-volume:
    external: true
  audit-share-ass-volume:
    external: true