version: '3.4'
services:
  audit-share-share:
    image: alfresco-share-audit-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-share-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: audit-share-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"

  audit-share-acs:
    image: alfresco-content-services-audit-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-share-platform-docker/target
      network: host
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      OVERRIDE_JAVA_OPTS: ""
      JAVA_OPTS: "
        -Dsolr.alfresco.port.ssl=8983
        $$OVERRIDE_JAVA_OPTS
      "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - audit-share-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - audit-share-postgres

  audit-share-postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - audit-share-db-volume:/var/lib/postgresql/data

  audit-share-ass:
    image: ${docker.ass.image}:${alfresco.ass.version}
    environment:
      SOLR_ALFRESCO_HOST: audit-share-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: audit-share-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS: "
        -Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - audit-share-ass-volume:/opt/alfresco-search-services/contentstore
      - audit-share-ass-volume:/opt/alfresco-search-services/data

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.0.1
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      ACTIVEMQ_USER: "admin"
      ACTIVEMQ_PASSWORD: "admin"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8090:8090"
    links:
      - activemq

  # Block to comment in Community version
  # transform-router:
  #   image: quay.io/alfresco/alfresco-transform-router:3.0.0
  #   environment:
  #     JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
  #     ACTIVEMQ_URL: "nio://activemq:61616"
  #     CORE_AIO_URL : "http://transform-core-aio:8090"
  #     FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
  #   ports:
  #     - 8095:8095
  #   links:
  #     - activemq

  # shared-file-store:
  #   image: quay.io/alfresco/alfresco-shared-file-store:3.0.0
  #   # Community : alfresco/alfresco-shared-file-store:0.16.1
  #   environment:
  #     JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
  #     scheduler.content.age.millis: 86400000
  #     scheduler.cleanup.interval: 86400000
  #   ports:
  #     - 8099:8099
  #   volumes:
  #     - sfs-data:/tmp/Alfresco/sfs

#  transform-dte-engine:
#    image: alfresco/transform-dte-engine:2.4.0
#    environment:
#      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80 -DdteServerUrl=http://alfresco-dte.dvt.cloud.priv.atolcd.com:8080/transformation-backend"
#      ACTIVEMQ_URL: "nio://activemq:61616"
#      ACTIVEMQ_USER: "admin"
#      ACTIVEMQ_PASSWORD: "admin"
#      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
#    ports:
#      - 8091:8090
#    links:
#      - activemq

  activemq:
    image: ${docker.activemq.image}:${activemq.version}
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

volumes:
  audit-share-acs-volume:
    external: true
  audit-share-db-volume:
    external: true
  audit-share-ass-volume:
    external: true
  # sfs-data:
  #   driver_opts:
  #     type: tmpfs
  #     device: tmpfs